name: Force-sync upstream every 30 min

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 拉取上游（放在 ./upstream）
      - uses: actions/checkout@v4
        with:
          repository: Mursor/LIVE
          ref: main
          path: upstream
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. 拉取自己的仓库（当前目录）
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      # 3. 备份 force-sync.yml → 清空仓库 → 复制上游 → 恢复 force-sync.yml
      - run: |
          # 备份当前 force-sync.yml
          cp .github/workflows/force-sync.yml /tmp/force-sync.yml
          # 清空仓库（除 .git）
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          # 把上游所有文件复制进来
          cp -a upstream/. .
          # 恢复 force-sync.yml
          mkdir -p .github/workflows
          mv /tmp/force-sync.yml .github/workflows/force-sync.yml
          # 提交 & 强制推送
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "force sync from Mursor/LIVE $(date -u)" || true
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main
