name: Force-sync with upstream every 30 min

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 拉取上游
      - uses: actions/checkout@v4
        with:
          repository: Mursor/LIVE
          ref: main
          path: upstream

      # 2. 拉取自己仓库（用默认 origin）
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      # 3. 覆盖并保留 workflows
      - run: |
          # 备份 workflow
          cp -r .github/workflows /tmp/workflows
          # 清空仓库（保留 .git）
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          # 拷贝上游
          cp -a upstream/. . || true
          # 恢复 workflow
          rm -rf .github/workflows
          cp -r /tmp/workflows .github/
          # 提交并强制推到自己仓库
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "force sync from upstream $(date -u)" || true
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main
